### PR TITLE
[WIP] Initial commit of third party api integration.

### PR DESCRIPTION
**Pull request by juliancheal**
An API to rule them all. That or a way for third party applications such as: Gitter, Slack, etc. to interact with miq-bot.

### CODE REVIEW

**Comment by juliancheal** [comment]
@miq-bot add_label wip

**Comment by juliancheal** [comment]
> Checked commit juliancheal@bd327d6 with ruby 2.2.6, rubocop 0.47.1, and haml-lint 0.20.0
> 6 files checked, 3 offenses detected
> 
> spec/controllers/api_controller_spec.rb
> 
>  ❗️ - Line 3, Col 31 - Style/HashSyntax - Use hash rockets syntax.
>  ❗️ - Line 4, Col 1 - Style/EmptyLinesAroundBlockBody - Extra empty line detected at block body beginning.
> spec/helpers/api_helper_spec.rb
> 
>  ❗️ - Line 13, Col 27 - Style/HashSyntax - Use hash rockets syntax.

Darn you Rails autogenerate.

**Comment by chrisarcand** [comment]
What are you trying to accomplish here in the end? Integration to do what?

**Comment by juliancheal** [comment]
> What are you trying to accomplish here in the end? Integration to do what?

All the things. Just scoping out an idea to see about adding in third party things like, Gitter. So you could say

< miqbot assign chrisarcand pr #8954589435

**Comment by juliancheal** [comment]
Will look at this again in the future when time is available. Closing for now.

**Pull request closed without merging**
