### PR TITLE
Force haml-lint to use only RuboCop as his linter

### PR DESCRIPTION
**Pull request by skateman**

### CODE REVIEW

**Comment by martinpovolny** [comment]
solves issues seen in https://github.com/ManageIQ/manageiq/pull/2075

**Comment by Fryguy** [comment]
How does this solve those issues if only specs are  changed here.

**Comment by skateman** [comment]
This removes the extensive misleading rubocop warnings from haml-lint as you can see in Martin's PR above.

**Comment by skateman** [comment]
This can be also solved by changing the configuration file, so please do not merge!

**Pull request closed without merging**
