### PR TITLE
Replace Sidetiq with Sidecloq

### LINKED ISSUE #282: SideTiq is no longer maintained
According the SideTiq README, SideTiq is no longer going to be maintained because it would have to be rewritten to deal with the Sidekiq 5 update.  We may want to consider alternatives (though they may also run into the same rewrite problem).  Some that I've found:

- https://github.com/moove-it/sidekiq-scheduler
- https://github.com/ondrejbartas/sidekiq-cron (So far I prefer this one)

### PR DESCRIPTION
**Pull request by Fryguy**
Closes #282

https://github.com/mattyr/sidecloq

@bdunne @agrare Please review.

I need help verifying this because for some reason locally Rugged is having issues with my private keys...it's an unrelated issue, but it prevents me from testing with "real" repos like the sandbox.

Also, switching to Sidecloq should now unlock our Sidekiq version, since we are no longer dependent on celluloid.  I did not do that in this PR, but will do a couple followup PRs to unlock Sidekiq first to 5.2.latest and then to 6

### CODE REVIEW

**Comment by Fryguy** [comment]
Note that I intentionally did not include the TravisBuildKiller because I'm going to be killing that anyway in #610

**Comment by Fryguy** [comment]
Updated with a spec to ensure the configured sidecloq queue matches the corresponding class queue as those could go out of sync if you change on and not the other.  It would be nice if sidecloq pulled the queue name from the class if not defined, but alas.

**Comment by bdunne** [comment]
Who is putting things on the queue? Is it just the UI worker? I want to make sure that we don't have everything queued 3 times (UI + 2 queue workers).

**Comment by Fryguy** [comment]
Removed the extra test - turns out you don't need to configure the queues because sidecloq will use the class' queue.

**Comment by Fryguy** [comment]
> Who is putting things on the queue? Is it just the UI worker? I want to make sure that we don't have everything queued 3 times (UI + 2 queue workers).

Sidecloq (much like SideTiq) runs in each sidekiq process that we run, but since those processes share the same redis, a lock is stored in redis and sidecloq runs a leader election where one of the sidekiq processes becomes the leader process.  All of the scheduling happens in that one leader process.  If the leader goes down the other process will become the new leader.

**Pull request merged**
