### PR TITLE
Bug/82/restart travis 3 times

### PR DESCRIPTION
**Pull request by imtayadeway**
Stops the stalled job handler after 3 attempts to restart the travis build.

Note: I couldn't get the travis client to listen on my machine in development, so thus far have been unable to QA this bugfix. I've added tests in the meantime to help increase confidence here. The tests are pretty heavy on the setup side, but I've left them as is to add some pressure to maybe refactor the worker to reduce the number of dependencies it has.

Fixes https://github.com/ManageIQ/miq_bot/issues/82

### CODE REVIEW

**Comment by Fryguy** [comment]
LGTM :+1: @jrafanie Can you give a second set of eyes on this since you wrote the original component.  Also, can you hep out testing it?

**Comment by jrafanie** [comment]
@imtayadeway looks good, I can help you test it.

**Comment by imtayadeway** [comment]
@jrafanie great! the history is a little messy so i'll squash after QA.

We got everything to spin up, just appeard that our server wasn't listening to travis events. Do we need to add something special to our config?

cc/ @carbonin

**Comment by jrafanie** [comment]
@imtayadeway @carbonin 

You need to configure the repo for travis_event in config/settings.yml:

```diff
 travis_event:
-  enabled_repos: []
+  enabled_repos: ["miq-test/sandbox"]
```

Then, start it.  Create a PR on miq-test/sandbox that does `sleep (60 * 15)` in a test.

You should see these "skipping" log messages in the sidekiq log as soon as you open the PR. It will [skip the "build:created", etc. events](https://github.com/ManageIQ/miq_bot/blob/30b4737c255d83dc3abc6fc652d37edd98cec163/app/workers/travis_event_handlers/stalled_finished_job.rb#L22).

Ping me if you have any questions.

**Comment by imtayadeway** [comment]
Thanks @jrafanie for helping me debug this. It appears to be an issue with travis. It has surfaced in production:

https://github.com/ManageIQ/manageiq/pull/3364#issuecomment-119282537

There's an open issue which could be related:

https://github.com/travis-ci/travis.rb/issues/302

**Comment by jrafanie** [comment]
@imtayadeway we should come back to this, now that https://github.com/travis-ci/travis.rb/issues/302 is fixed as least on travis.rb master.

**Comment by imtayadeway** [comment]
@jrafanie sitll having no joy with this. tried with the new 1.8.0 release. i opened an issue here:

https://github.com/travis-ci/travis.rb/issues/304

**Comment by jrafanie** [comment]
@imtayadeway can you try by unlocking travis to >= 1.7.6?

I got this when bundling locally with ruby 2.2.2:
```
...
Installing typhoeus 0.7.3 (was 0.7.2)
Installing backports 3.6.6 (was 3.6.5)
Installing highline 1.7.3 (was 1.7.2)
Installing travis 1.8.0 (was 1.7.7)
```

Then, when I run the CLI monitor:
```
$ bundle exec travis monitor --org --debug
** Loading "/Users/joerafaniello/.travis/config.yml"
** Using notifications: Dummy
** GET "config"
**   took 0.1 seconds
** GET "users/"
**   took 0.45 seconds
Monitoring travis-ci.org:
2015-08-18 13:39:53 ManageIQ/manageiq#12440.7 passed
2015-08-18 13:40:02 ManageIQ/manageiq#12232.4 started
2015-08-18 13:40:44 ManageIQ/manageiq#12232.3 passed
2015-08-18 13:40:56 ManageIQ/manageiq#12232.5 started
```

**Comment by imtayadeway** [comment]
@jrafanie I can confirm that I get the same (or similar) results from the above snippet you pasted with travis gem version 1.8.0. However, I'm still unable to get anything from the snippet I made in https://github.com/travis-ci/travis.rb/issues/304 (which just a slightly modified version of that from the README), nor can I get the travis listener to respond to events in the sandbox repo. Do either of those work for you?

**Comment by imtayadeway** [comment]
Going to close this while it's not going anywhere. Will try again soon.

**Pull request closed without merging**
