### PR TITLE
Fix encoding issues when writing out blobs.

### PR DESCRIPTION
**Pull request by bdunne**
Fixes `Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8`

### CODE REVIEW

**Comment by bdunne** [comment]
@Fryguy @matthewd @himdel Please review.

**Comment by himdel** [comment]
I *think* so.. (I am sure that the `mode` arg does reach IO.open) .. but I haven't managed to reproduce that error with just `File.write('foo', 'Чук')` (or even `'Чук'.force_encoding(Encoding::ASCII_8BIT)`) so maybe there's something else... do you know what is the class and encoding (if String) of the thing that gets passed in?

**Comment by bdunne** [comment]
@himdel It's from a Rugged::Blob#content

**Comment by himdel** [comment]
Right.. that says it returns a String tagged as ASCII-8BIT.. which makes me think running  `File.write('foo', "\xd0\xa7\xd1\x83\xd0\xba".force_encoding('ASCII-8BIT'))` should fail with the same exception, right? Does it for you?

**Comment by bdunne** [comment]
@himdel You should be able to reproduce it in rails console as long as you have fetched the remote that contains the commit or refs/pull/*
```ruby
irb(main):001:0> require 'rugged'; r = Rugged::Repository.new("./")
=> #<Rugged::Repository:47126837857200 {path: "/home/bdunne/projects/redhat/manageiq/.git/"}>
irb(main):002:0> b = r.blob_at("e60999af89485a4d26a4d9b5d71a49768f5aa89a", "spec/lib/report_formater/c3_formatter_spec.rb")
=> #<Rugged::Blob:0x0055b917bf0da8 @owner=#<Rugged::Repository:47126837857200 {path: "/home/bdunne/projects/redhat/manageiq/.git/"}>>
irb(main):003:0> b.content
=> "include ReportsSpecHelper\n\ndescribe ReportFormatter::C3Formatter do\n  before(:each) do\n    allow(Charting).to receive(:backend).and_return(:c3)\n    allow(Charting).to receive(:format).and_return(:c3)\n  end\n  context '#build_numeric_chart_grouped' do\n    [true, false].each do |other|\n      it \"builds 2d numeric charts from summaries \#{other ? 'with' : 'without'} 'other'\" do\n        report = MiqReport.new(\n          :db          => \"Vm\",\n          :sortby      => [\"ext_management_system.name\"],\n          :order       => \"Descending\",\n          :cols        => %w(name num_cpu),\n          :include     => {\"ext_management_system\" => {\"columns\" => [\"name\"]}},\n          :col_order   => %w(name num_cpu ext_management_system.name),\n          :headers     => [\"Name\", \"Number of CPUs\", \"Cloud/Infrastructure Provider Name\"],\n          :dims        => 1,\n          :group       => \"y\",\n          :rpt_options => {:summary => {:hide_detail_rows => false}},\n          :col_options => {\"num_cpu\" => {:grouping => [:avg, :max, :min, :total]},\n                           \"name\"    => {:break_label => \"Cloud/Infrastructure Provider : Name: \"}},\n          :graph       => {:type => \"Column\", :mode => \"values\", :column => \"Vm-num_cpu:total\", :count => 2, :other => other},\n          :extras      => {},\n        )\n\n        report.table = Ruport::Data::Table.new(\n          :column_names => %w(name num_cpu ext_management_system.name id),\n          :data         => [\n            [\"bar\", 1, system_name_1 = 'blah', 352],\n            [\"foo\", 3, system_name_1,          353],\n            [\"pat\", 1, system_name_2 = 'bleh', 354],\n            [\"mat\", 1, system_name_2,          355],\n            [\"cuk\", 1, system_name_3 = 'blrg', 356],\n            [\"gek\", 2, system_name_3,          357],\n            [\"tik\", 1, system_name_4 = 'blud', 358],\n            [\"tak\", 1, system_name_4,          359],\n          ],\n        )\n\n        expect_any_instance_of(described_class).to receive(:build_numeric_chart_grouped).once.and_call_original\n        render_report(report)\n        expect(report.chart[:data][:columns][0][1]).to eq(4.0)\n        expect(report.chart[:data][:columns][0][-1]).to eq(4) if other\n      end\n    end\n  end\n\n  context '#build_numeric_chart_simple' do\n    let(:report) do\n      report = MiqReport.new(\n        :db          => \"Host\",\n        :cols        => %w(name ram_size),\n        :col_order   => %w(name ram_size),\n        :headers     => [\"Name\", \"RAM Size (MB)\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(name),\n        :group       => nil,\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Host-ram_size\", :count => 10, :other => false},\n        :dims        => 1,\n        :col_options => {},\n        :extras      => {},\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(name ram_size id),\n        :data         => [\n          ['jenda',  512, 1],\n          ['ladas', 1024, 2],\n          ['joker', 2024, 3],\n        ]\n      )\n\n      report\n    end\n\n    it \"report chart have right data in ascending order\" do\n      report.col_formats = [nil, :general_number_precision_0]\n      render_report(report)\n      expect(report.chart[:data][:columns][0].count).to eq(report.table.data.count + 1)\n      expect(report.chart[:data][:columns][0][1]).to eq(2024)\n    end\n\n    it \"handles null data in chart column\" do\n      report = MiqReport.new(\n        :db          => \"Vm\",\n        :cols        => %w(name),\n        :include     => {\"hardware\" => {\"columns\" => %w(cpu_speed cpu_sockets memory_mb)}},\n        :col_order   => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb),\n        :headers     => [\"Name\", \"Hardware CPU Speed\", \"Hardware Number of CPUs\", \"Hardware RAM\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(name),\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Vm.hardware-cpu_sockets\", :count => 10, :other => true},\n        :dims        => 1,\n        :col_options => {},\n        :rpt_options => {},\n        :extras      => {},\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb id),\n        :data         => [\n          [\"\xD0\xA7\xD1\x83\xD0\xBA\", nil, 4,   6_144, 42],\n          [\"\xD0\x93\xD0\xB5\xD0\xBA\", nil, nil, 1_024, 49],\n        ],\n      )\n\n      expect_any_instance_of(described_class).to receive(:build_numeric_chart_simple).once.and_call_original\n      render_report(report)\n    end\n  end\n\n  context '#build_numeric_chart_simple' do\n    [true, false].each do |other|\n      it \"builds 2d numeric charts \#{other ? 'with' : 'without'} 'other'\" do\n        report = MiqReport.new(\n          :db          => \"Host\",\n          :sortby      => %w(name),\n          :order       => \"Descending\",\n          :cols        => %w(name v_total_vms),\n          :include     => {},\n          :col_order   => %w(name v_total_vms),\n          :headers     => [\"Name\", \"Total VMs\"],\n          :dims        => 1,\n          :group       => nil,\n          :rpt_options => {},\n          :col_options => {},\n          :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Host-v_total_vms\", :count => 4, :other => other},\n          :extras      => {},\n        )\n\n        report.table = Ruport::Data::Table.new(\n          :column_names => %w(name v_total_vms id),\n          :data         => [\n            [host_name_1 = \"bar\", 15, 1352],\n            [\"foo\", 14,               1353],\n            [\"foo\", 3,                1354],\n            [\"foo\", 2,                1355],\n            [\"foo\", 1,                1356],\n            [\"foo\", 0,                1357],\n          ],\n        )\n\n        expect_any_instance_of(described_class).to receive(:build_numeric_chart_simple).once.and_call_original\n        render_report(report)\n        expect(report.chart[:data][:columns][0][1]).to eq(15)\n        expect(report.chart[:data][:columns][0][-1]).to eq(1) if other\n      end\n    end\n\n    it \"handles null data in chart column\" do\n      report = MiqReport.new(\n        :db          => \"Vm\",\n        :cols        => %w(name),\n        :include     => {\"hardware\" => {\"columns\" => %w(cpu_speed cpu_sockets memory_mb)}},\n        :col_order   => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb),\n        :headers     => [\"Name\", \"Hardware CPU Speed\", \"Hardware Number of CPUs\", \"Hardware RAM\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(name),\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Vm.hardware-cpu_sockets\", :count => 10, :other => true},\n        :dims        => 1,\n        :col_options => {},\n        :rpt_options => {},\n        :extras      => {},\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb id),\n        :data         => [\n          [\"\xD0\xA7\xD1\x83\xD0\xBA\", nil, 4,   6_144, 42],\n          [\"\xD0\x93\xD0\xB5\xD0\xBA\", nil, nil, 1_024, 49],\n        ],\n      )\n\n      expect_any_instance_of(described_class).to receive(:build_numeric_chart_simple).once.and_call_original\n      render_report(report)\n    end\n  end\n\n  context '#build_numeric_chart_grouped_2dim' do\n    [true, false].each do |other|\n      it \"builds 3d numeric charts \#{other ? 'with' : 'without'} 'other'\" do\n        report = MiqReport.new(\n          :db          => \"Vm\",\n          :cols        => %w(os_image_name mem_cpu),\n          :include     => {\"ext_management_system\" => {\"columns\" => [\"name\"]}},\n          :col_order   => %w(ext_management_system.name os_image_name mem_cpu),\n          :headers     => [\"Cloud/Infrastructure Provider Name\", \"OS Name\", \"Memory\"],\n          :order       => \"Ascending\",\n          :sortby      => %w(ext_management_system.name os_image_name),\n          :group       => \"y\",\n          :graph       => {:type => \"StackedBar\", :mode => \"values\", :column => \"Vm-mem_cpu:total\", :count => 2, :other => other},\n          :dims        => 2,\n          :col_options => {\"name\" => {:break_label => \"Cloud/Infrastructure Provider : Name: \"}, \"mem_cpu\" => {:grouping => [:total]}},\n          :rpt_options => {:summary => {:hide_detail_rows => false}},\n          :extras      => {},\n        )\n\n        report.table = Ruport::Data::Table.new(\n          :column_names => %w(os_image_name mem_cpu ext_management_system.name id),\n          :data         => [\n            [\"linux_centos\", 6_144, \"MTC-RHEVM-3.0\", 67],\n            [\"linux_centos\", 512,   \"MTC-RHEVM-3.0\", 167],\n            [\"widloze\",      1_024, \"MTC-RHEVM-3.0\", 68],\n            [\"linux_centos\", 4_096, \"openslack\",     70],\n            [\"widloze\",      2_048, \"openslack\",     69],\n            [\"widloze\",      1_024, \"openslack\",     71],\n            [\"linux_centos\", 1_024, \"ec2\",           72],\n            [\"\",             0,     \"\",              79],\n          ],\n        )\n\n        expect_any_instance_of(described_class).to receive(:build_numeric_chart_grouped_2dim).once.and_call_original\n        render_report(report)\n        expect(report.chart[:data][:columns][0][1]).to eq(6_656)\n        expect(report.chart[:data][:columns][0][2]).to eq(4_096)\n        expect(report.chart[:data][:columns][1][1]).to eq(1_024)\n        expect(report.chart[:data][:columns][0][-1]).to eq(1_024) if other\n      end\n    end\n\n    it 'handles namespace-prefixed class names in chart column' do\n      report = MiqReport.new(\n        :db          => \"ManageIQ::Providers::InfraManager::Vm\",\n        :cols        => %w(os_image_name cpu_total_cores num_cpu),\n        :include     => {\"host\" => {\"columns\" => %w(name)}},\n        :col_order   => %w(os_image_name host.name cpu_total_cores num_cpu),\n        :headers     => [\"OS Name\", \"Host / Node Name\", \"Number of CPU Cores\", \"Number of CPUs\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(host.name os_image_name),\n        :group       => \"y\",\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"ManageIQ::Providers::InfraManager::Vm-num_cpu:total\", :count => 10, :other => true},\n        :dims        => 2,\n        :col_options => {\"name\" => {:break_label => \"Host / Node : Name: \"}, \"num_cpu\" => {:grouping => [:total]}},\n        :rpt_options => {:summary => {:hide_detail_rows => false}},\n        :extras      => {}\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(os_image_name cpu_total_cores num_cpu host.name id),\n        :data         => [\n          [\"linux_centos\", 8, 2, \"MTC-RHEVM-3.0\", 67],\n        ]\n      )\n\n      expect_any_instance_of(described_class).to receive(:build_numeric_chart_grouped_2dim).once.and_call_original\n      render_report(report)\n    end\n  end\nend\n"
irb(main):004:0> File.write("./test_file.rb", b.content)
Encoding::UndefinedConversionError: "\xD0" from ASCII-8BIT to UTF-8
	from (irb):6:in `write'
	from (irb):6
	from /home/bdunne/.gem/ruby/2.2.4/bundler/gems/rails-a4ef62279d69/railties/lib/rails/commands/console.rb:65:in `start'
	from /home/bdunne/.gem/ruby/2.2.4/bundler/gems/rails-a4ef62279d69/railties/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/bdunne/.gem/ruby/2.2.4/bundler/gems/rails-a4ef62279d69/railties/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/bdunne/.gem/ruby/2.2.4/bundler/gems/rails-a4ef62279d69/railties/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/bdunne/.gem/ruby/2.2.4/bundler/gems/rails-a4ef62279d69/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by bdunne** [comment]
@himdel Yes, that fails with the same exception for me.

**Comment by himdel** [comment]
@bdunne Interesting.. for me, it does..

```
irb(main):001:0> require 'rugged'; r = Rugged::Repository.new("./")
=> #<Rugged::Repository:47338880997920 {path: "/home/himdel/manageiq/.git/"}>
irb(main):002:0> b = r.blob_at("e60999af89485a4d26a4d9b5d71a49768f5aa89a", "spec/lib/report_formater/c3_formatter_spec.rb")
=> #<Rugged::Blob:0x00561be25c4230 @owner=#<Rugged::Repository:47338880997920 {path: "/home/himdel/manageiq/.git/"}>>
irb(main):003:0> b.content
=> "include ReportsSpecHelper\n\ndescribe ReportFormatter::C3Formatter do\n  before(:each) do\n    allow(Charting).to receive(:backend).and_return(:c3)\n    allow(Charting).to receive(:format).and_return(:c3)\n  end\n  context '#build_numeric_chart_grouped' do\n    [true, false].each do |other|\n      it \"builds 2d numeric charts from summaries \#{other ? 'with' : 'without'} 'other'\" do\n        report = MiqReport.new(\n          :db          => \"Vm\",\n          :sortby      => [\"ext_management_system.name\"],\n          :order       => \"Descending\",\n          :cols        => %w(name num_cpu),\n          :include     => {\"ext_management_system\" => {\"columns\" => [\"name\"]}},\n          :col_order   => %w(name num_cpu ext_management_system.name),\n          :headers     => [\"Name\", \"Number of CPUs\", \"Cloud/Infrastructure Provider Name\"],\n          :dims        => 1,\n          :group       => \"y\",\n          :rpt_options => {:summary => {:hide_detail_rows => false}},\n          :col_options => {\"num_cpu\" => {:grouping => [:avg, :max, :min, :total]},\n                           \"name\"    => {:break_label => \"Cloud/Infrastructure Provider : Name: \"}},\n          :graph       => {:type => \"Column\", :mode => \"values\", :column => \"Vm-num_cpu:total\", :count => 2, :other => other},\n          :extras      => {},\n        )\n\n        report.table = Ruport::Data::Table.new(\n          :column_names => %w(name num_cpu ext_management_system.name id),\n          :data         => [\n            [\"bar\", 1, system_name_1 = 'blah', 352],\n            [\"foo\", 3, system_name_1,          353],\n            [\"pat\", 1, system_name_2 = 'bleh', 354],\n            [\"mat\", 1, system_name_2,          355],\n            [\"cuk\", 1, system_name_3 = 'blrg', 356],\n            [\"gek\", 2, system_name_3,          357],\n            [\"tik\", 1, system_name_4 = 'blud', 358],\n            [\"tak\", 1, system_name_4,          359],\n          ],\n        )\n\n        expect_any_instance_of(described_class).to receive(:build_numeric_chart_grouped).once.and_call_original\n        render_report(report)\n        expect(report.chart[:data][:columns][0][1]).to eq(4.0)\n        expect(report.chart[:data][:columns][0][-1]).to eq(4) if other\n      end\n    end\n  end\n\n  context '#build_numeric_chart_simple' do\n    let(:report) do\n      report = MiqReport.new(\n        :db          => \"Host\",\n        :cols        => %w(name ram_size),\n        :col_order   => %w(name ram_size),\n        :headers     => [\"Name\", \"RAM Size (MB)\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(name),\n        :group       => nil,\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Host-ram_size\", :count => 10, :other => false},\n        :dims        => 1,\n        :col_options => {},\n        :extras      => {},\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(name ram_size id),\n        :data         => [\n          ['jenda',  512, 1],\n          ['ladas', 1024, 2],\n          ['joker', 2024, 3],\n        ]\n      )\n\n      report\n    end\n\n    it \"report chart have right data in ascending order\" do\n      report.col_formats = [nil, :general_number_precision_0]\n      render_report(report)\n      expect(report.chart[:data][:columns][0].count).to eq(report.table.data.count + 1)\n      expect(report.chart[:data][:columns][0][1]).to eq(2024)\n    end\n\n    it \"handles null data in chart column\" do\n      report = MiqReport.new(\n        :db          => \"Vm\",\n        :cols        => %w(name),\n        :include     => {\"hardware\" => {\"columns\" => %w(cpu_speed cpu_sockets memory_mb)}},\n        :col_order   => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb),\n        :headers     => [\"Name\", \"Hardware CPU Speed\", \"Hardware Number of CPUs\", \"Hardware RAM\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(name),\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Vm.hardware-cpu_sockets\", :count => 10, :other => true},\n        :dims        => 1,\n        :col_options => {},\n        :rpt_options => {},\n        :extras      => {},\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb id),\n        :data         => [\n          [\"\xD0\xA7\xD1\x83\xD0\xBA\", nil, 4,   6_144, 42],\n          [\"\xD0\x93\xD0\xB5\xD0\xBA\", nil, nil, 1_024, 49],\n        ],\n      )\n\n      expect_any_instance_of(described_class).to receive(:build_numeric_chart_simple).once.and_call_original\n      render_report(report)\n    end\n  end\n\n  context '#build_numeric_chart_simple' do\n    [true, false].each do |other|\n      it \"builds 2d numeric charts \#{other ? 'with' : 'without'} 'other'\" do\n        report = MiqReport.new(\n          :db          => \"Host\",\n          :sortby      => %w(name),\n          :order       => \"Descending\",\n          :cols        => %w(name v_total_vms),\n          :include     => {},\n          :col_order   => %w(name v_total_vms),\n          :headers     => [\"Name\", \"Total VMs\"],\n          :dims        => 1,\n          :group       => nil,\n          :rpt_options => {},\n          :col_options => {},\n          :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Host-v_total_vms\", :count => 4, :other => other},\n          :extras      => {},\n        )\n\n        report.table = Ruport::Data::Table.new(\n          :column_names => %w(name v_total_vms id),\n          :data         => [\n            [host_name_1 = \"bar\", 15, 1352],\n            [\"foo\", 14,               1353],\n            [\"foo\", 3,                1354],\n            [\"foo\", 2,                1355],\n            [\"foo\", 1,                1356],\n            [\"foo\", 0,                1357],\n          ],\n        )\n\n        expect_any_instance_of(described_class).to receive(:build_numeric_chart_simple).once.and_call_original\n        render_report(report)\n        expect(report.chart[:data][:columns][0][1]).to eq(15)\n        expect(report.chart[:data][:columns][0][-1]).to eq(1) if other\n      end\n    end\n\n    it \"handles null data in chart column\" do\n      report = MiqReport.new(\n        :db          => \"Vm\",\n        :cols        => %w(name),\n        :include     => {\"hardware\" => {\"columns\" => %w(cpu_speed cpu_sockets memory_mb)}},\n        :col_order   => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb),\n        :headers     => [\"Name\", \"Hardware CPU Speed\", \"Hardware Number of CPUs\", \"Hardware RAM\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(name),\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"Vm.hardware-cpu_sockets\", :count => 10, :other => true},\n        :dims        => 1,\n        :col_options => {},\n        :rpt_options => {},\n        :extras      => {},\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(name hardware.cpu_speed hardware.cpu_sockets hardware.memory_mb id),\n        :data         => [\n          [\"\xD0\xA7\xD1\x83\xD0\xBA\", nil, 4,   6_144, 42],\n          [\"\xD0\x93\xD0\xB5\xD0\xBA\", nil, nil, 1_024, 49],\n        ],\n      )\n\n      expect_any_instance_of(described_class).to receive(:build_numeric_chart_simple).once.and_call_original\n      render_report(report)\n    end\n  end\n\n  context '#build_numeric_chart_grouped_2dim' do\n    [true, false].each do |other|\n      it \"builds 3d numeric charts \#{other ? 'with' : 'without'} 'other'\" do\n        report = MiqReport.new(\n          :db          => \"Vm\",\n          :cols        => %w(os_image_name mem_cpu),\n          :include     => {\"ext_management_system\" => {\"columns\" => [\"name\"]}},\n          :col_order   => %w(ext_management_system.name os_image_name mem_cpu),\n          :headers     => [\"Cloud/Infrastructure Provider Name\", \"OS Name\", \"Memory\"],\n          :order       => \"Ascending\",\n          :sortby      => %w(ext_management_system.name os_image_name),\n          :group       => \"y\",\n          :graph       => {:type => \"StackedBar\", :mode => \"values\", :column => \"Vm-mem_cpu:total\", :count => 2, :other => other},\n          :dims        => 2,\n          :col_options => {\"name\" => {:break_label => \"Cloud/Infrastructure Provider : Name: \"}, \"mem_cpu\" => {:grouping => [:total]}},\n          :rpt_options => {:summary => {:hide_detail_rows => false}},\n          :extras      => {},\n        )\n\n        report.table = Ruport::Data::Table.new(\n          :column_names => %w(os_image_name mem_cpu ext_management_system.name id),\n          :data         => [\n            [\"linux_centos\", 6_144, \"MTC-RHEVM-3.0\", 67],\n            [\"linux_centos\", 512,   \"MTC-RHEVM-3.0\", 167],\n            [\"widloze\",      1_024, \"MTC-RHEVM-3.0\", 68],\n            [\"linux_centos\", 4_096, \"openslack\",     70],\n            [\"widloze\",      2_048, \"openslack\",     69],\n            [\"widloze\",      1_024, \"openslack\",     71],\n            [\"linux_centos\", 1_024, \"ec2\",           72],\n            [\"\",             0,     \"\",              79],\n          ],\n        )\n\n        expect_any_instance_of(described_class).to receive(:build_numeric_chart_grouped_2dim).once.and_call_original\n        render_report(report)\n        expect(report.chart[:data][:columns][0][1]).to eq(6_656)\n        expect(report.chart[:data][:columns][0][2]).to eq(4_096)\n        expect(report.chart[:data][:columns][1][1]).to eq(1_024)\n        expect(report.chart[:data][:columns][0][-1]).to eq(1_024) if other\n      end\n    end\n\n    it 'handles namespace-prefixed class names in chart column' do\n      report = MiqReport.new(\n        :db          => \"ManageIQ::Providers::InfraManager::Vm\",\n        :cols        => %w(os_image_name cpu_total_cores num_cpu),\n        :include     => {\"host\" => {\"columns\" => %w(name)}},\n        :col_order   => %w(os_image_name host.name cpu_total_cores num_cpu),\n        :headers     => [\"OS Name\", \"Host / Node Name\", \"Number of CPU Cores\", \"Number of CPUs\"],\n        :order       => \"Ascending\",\n        :sortby      => %w(host.name os_image_name),\n        :group       => \"y\",\n        :graph       => {:type => \"Bar\", :mode => \"values\", :column => \"ManageIQ::Providers::InfraManager::Vm-num_cpu:total\", :count => 10, :other => true},\n        :dims        => 2,\n        :col_options => {\"name\" => {:break_label => \"Host / Node : Name: \"}, \"num_cpu\" => {:grouping => [:total]}},\n        :rpt_options => {:summary => {:hide_detail_rows => false}},\n        :extras      => {}\n      )\n\n      report.table = Ruport::Data::Table.new(\n        :column_names => %w(os_image_name cpu_total_cores num_cpu host.name id),\n        :data         => [\n          [\"linux_centos\", 8, 2, \"MTC-RHEVM-3.0\", 67],\n        ]\n      )\n\n      expect_any_instance_of(described_class).to receive(:build_numeric_chart_grouped_2dim).once.and_call_original\n      render_report(report)\n    end\n  end\nend\n"
irb(main):004:0> File.write("./test_file.rb", b.content)
=> 10694
```

Also, wow that was a **huge** fetch :) (prs)

**Comment by himdel** [comment]
the output for `b.content` looks the same, so probably something environmental...

```sh
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

one of these maybe?

**Comment by bdunne** [comment]
```
$ ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by himdel** [comment]
OK I'm stumped :D

**Comment by himdel** [comment]
@matthewd , @Fryguy , anyone? :)

**Pull request merged**
