### PR TITLE
Avoid having :pull_request => nil

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Comment by chrisarcand** [comment]
Ugh, I'm sad we use this gem here, too 😩

**Comment by bdunne** [comment]
For this case, you could change rails :)

**Comment by Fryguy** [comment]
Yeah, I don't see why we can't use column defaults here for most stuff (except maybe the serialized arrays)

**Comment by Fryguy** [comment]
> Ugh, I'm sad we use this gem here, too 😩

This was a playground for the usage of that gem, so technically this was first :)

**Pull request merged**
