### PR TITLE
Replace GitHubApi with OctokitWrappers

### PR DESCRIPTION
**Pull request by chrisarcand**
* Removes GitHubApi module completely
* Adds OctokitWrappers, a module with delegators that seamlessly
adds our logic to ordinary Octokit objects and responses. No more passing
around a dozen parameters to every little class.
* Completely rewrites Github notification monitor spec more betterer. 

Don't be scared of the diff. A lot of the changes are moves and/or direct
changes from making indirect Github calls with the previous wrapper to just using Octokit.
Half of it alone is just completely rewriting the GHNM specs.

### CODE REVIEW

**Comment by chrisarcand** [comment]
@miq-bot add_label wip

**Comment by chrisarcand** [comment]
@miq-bot remove_label wip

**Comment by chrisarcand** [comment]
@Fryguy Please review

**Comment by Fryguy** [comment]
😱

**Comment by jrafanie** [comment]
> Don't be scared of the diff. A lot of the changes are moves and/or direct
> changes from making indirect Github calls with the previous wrapper to just using Octokit.
> Half of it alone is just completely rewriting the GHNM specs.

As long as git praise points at @chrisarcand it's all good 😉

**Comment by chrisarcand** [comment]
Should also note that future moves to this pattern will be in smaller PRs ^_^ The Github notification monitor is by far the largest thing, utilizing a good portion of the module I wanted to remove entirely.

**Comment by Fryguy** [comment]
> Adds pry-rails, because I'm sick of editing the gem/lockfile in dev

Says it adds pry-rails...doesn't actually add pry-rails

**Comment by Fryguy** [comment]
Where does the username/password get configured? I can't find it.

**Comment by chrisarcand** [comment]
> Says it adds pry-rails...doesn't actually add pry-rails

Oops, forgot to remove from comments. I decided no, I prolly shouldn't do that ^_^ I kept going back and forth, I actually find `pry-remote` more useful for debugging workers, blah blah blah and just decided to remove it altogether. 

> Where does the username/password get configured? I can't find it.

https://github.com/ManageIQ/miq_bot/blob/master/config/initializers/octokit.rb

**Comment by Fryguy** [comment]
Ah ok, I was expecting it in config/initializer/services_initializer.rb with the rest of them.

**Pull request merged**
