### PR TITLE
Run the issue manager worker if there isn't already one :open_mouth:

### PR DESCRIPTION
**Pull request by jrafanie**
Fixes an issue we saw where an issue manager worker started while
another was running.

### CODE REVIEW

**Comment by jrafanie** [comment]
This was a @bdunne @Fryguy @jrafanie production

**Comment by imtayadeway** [comment]
:+1: LGTM. Apologies, as I am sure I broke this :disappointed:

**Comment by jrafanie** [comment]
> LGTM. Apologies, as I am sure I broke this

No worries...  It was an easy fix now that it's a worker.

**Comment by jrafanie** [comment]
Tests passed locally :green_heart:  after fixing the missing `include MiqToolsServices::SidekiqWorkerMixin`

**Pull request merged**
