### PR TITLE
Rename models

### PR DESCRIPTION
**Pull request by imtayadeway**
don't think there's an issue for this, but I'm pretty sure we talked about this change:

* `CommitMonitorRepo` => `Repo`
* `CommitMonitorBranch` => `Branch`

### CODE REVIEW

**Comment by Fryguy** [comment]
IT'S LIKE YOU'RE READING MY MIND... :open_mouth: 

The only thing I was going to do different was name them GitRepo and GitBranch.  Thoughts?

**Comment by Fryguy** [comment]
And no, I don't think we had talked about it...But I was literally going to change this right after my batch support changes :smile:

**Comment by imtayadeway** [comment]
@Fryguy nice! hehe

I think what I like about `Repo`/`Branch` is that it's natural to say that a `repo` has many `branches`, and everything Just Works :tm: etc..

What I like about `GitRepo`/`GitBranch` is that it's more immediately obvious what these things are modeling from the outside without any further context. So I'm kinda on the fence :grinning:

**Comment by Fryguy** [comment]
Been thinking about it and I'm good with Repo / Branch.  But, alas, it has conflicts

**Comment by imtayadeway** [comment]
@Fryguy just rebased and incorporated some new stuff along the way.

**Pull request merged**
