### PR TITLE
Add a repos folder, but ignore its contents.

### PR DESCRIPTION
**Pull request by imtayadeway**
* Adds a `repos` folder so it does not need to be created in development steps
* Ignores anything in the `repos` folder so things added there for development are not tracked.
* Removes the corresponding step from the README

### CODE REVIEW

**Comment by Fryguy** [comment]
Hmmm... This was one of the things I was not sure about in the original docs...I really don't think the repos should physically live in the same repo...would prefer if they lived externally (which is how we have it set up in deployment)

@brandondunne Thoughts?

**Comment by Fryguy** [comment]
Actually, I've completely changed my mind and I love this repos directory idea as a default.  One of the things we want the bot to do is to autoclone the repos, which should make adding new ones easier.  Having the repos directory keeps it isolated from other repos that we might have locally.

However, does it make sense to have it configurable?  I'm thinking, keep the repos directory in the Rails root as the default, but perhaps allow overriding in a config file.  This might be useful in deployment if we want all the git repos to live elsewhere (say on an NFS share).  Having it configurable also allows different directories in prod/dev/test.

**Comment by jrafanie** [comment]
> This might be useful in deployment if we want all the git repos to live elsewhere (say on an NFS share). Having it configurable also allows different directories in prod/dev/test.

Let's make it configurable when we know we need to do it.

I like this change.  :+1:

**Comment by imtayadeway** [comment]
that sounds fun! anything to do be done at this time?

**Pull request merged**
