### PR TITLE
Declare dependency on xmlrpc

### PR DESCRIPTION
**Pull request by bdunne**
Allow development with ruby 2.5

### CODE REVIEW

**Comment by chrisarcand** [comment]
If we do this, the lockfile will change on some systems but not others causing a dirty change. We currently check in the lockfile, as should be the case when you're developing on an application (as opposed to a gem).

As we can't use 2.5 features anyway because it needs to be compatible with 2.3 for ManageIQ, I don't know why we'd want to do this - but if you really really want to, would it conflict if  you added it regardless of it being needed for < 2.5 (to keep the lockfiles the same in both cases...?)

**Comment by chrisarcand** [comment]
@bdunne Done any trying out of this on < 2.5 to make sure the gem doesn't screw with the existing lib?

**Comment by bdunne** [comment]
Nope.  I can close this if we're not ready yet (since it will be quite a while before we're on 2.5) or mark as WIP and collect any other 2.5 issues in this PR as well

**Comment by chrisarcand** [comment]
¯\\\_(ツ)_/¯ Doesn't matter to me! I'm cool with whatever, as long as the lockfile is still able to keep env parity as it's designed to do and the lib doesn't screw with the core one.

**Comment by bdunne** [comment]
@miq-bot add_reviewer @Fryguy

**Comment by bdunne** [comment]
@miq-bot add_reviewer @Fryguy

**Comment by juliancheal** [comment]
@bdunne This is fixed by #430

**Comment by Fryguy** [comment]
Closed via #434

**Pull request closed without merging**
