### PR TITLE
Add (suggestion for) better regexp for puts

### PR DESCRIPTION
**Pull request by NickLaMuro**
This is less of a "new feature" and more of a way we should consider handling checking for `puts` in our `config/settings.yml`.

In the current config by just looking for `puts` as a "word", we will end up flagging it when it is in comments or just in an everyday sentence (you know... since it is a 'word' in the English dictionary).

The suggestion I am proposing basically is to make the `puts` check a regexp that will not match against any line that includes a `#` proceeding the word, and I re-worked the specs to show how that would work.

* * *

The alternative to this approach would be to add the following regexp matcher preamble:

```ruby
/^([^#]+|)\b#{my_bad_word}\b/
```

To the "word" `Regexp` for of the content checker.  I figured this was more invasive so I went with the above, but might be more flexible overall and something to consider.

### CODE REVIEW

**Comment by NickLaMuro** [comment]
> Some comments on commit NickLaMuro@d094e70
>
> **spec/workers/commit_monitor_handlers/commit_range/github_pr_commenter/diff_content_checker_spec.rb**
>
> * [ ] ⚠️ - 44 - Detected puts. Remove all debugging statements.
> * [ ] ⚠️ - 7 - Detected puts. Remove all debugging statements.
> ...

Oh, thanks @miq-bot for showing me _**exactly**_ what was infuriating about this feature in the first place...

😡

**Comment by juliancheal** [comment]
LGTM 👍 can you fix the `puts` errors above? :trollface:

**Comment by NickLaMuro** [comment]
> LGTM 👍 can you fix the puts errors above? :trollface:

@juliancheal (and I guess a @Fryguy FYI):  This ends up requiring a config change as well to do it, so to actually remove this, we would need to update the regexp in the config to what I have in the specs.

**Comment by Fryguy** [comment]
Yup..working on it

**Comment by NickLaMuro** [comment]
Thanks, and just making sure... my PR descriptions in the past have known to cause the "glazing of the eyes"

**Pull request merged**
